# This is a SCons script that builds a C++ project.

import os

env = Environment(ENV=os.environ)

build_filename = '../build/a.out'

sources = [
	Glob('*.cpp'),		# Add all cpp files.
]

env.Append(CCFLAGS=[
	'-Wall',
	'-g',
	'-std=c++11',
])

env.Append(LIBS = [
	'GL',
	'GLU',
])

env.Append(LIBPATH = [
	'/usr/local/lib',
])

env.ParseConfig('pkg-config --cflags glfw3')
env.ParseConfig('pkg-config --libs glfw3')


env.Program(target = build_filename, source = sources)

