#!/usr/bin/python
# This is a SCons script that builds a C++ project.

import os

env = Environment(ENV=os.environ)
Tool('g++')(env)

build_filename = '../build/a.out'

sources = [
	Glob('*.cpp')		# Add all cpp files.
]

env.Append(CCFLAGS=[
	'-Wall',
	'-g',
	'-std=c++11'
])

env.Append(CPPPATH = [
])

env.Append(LIBS = [
])

env.Append(LIBPATH = [
])


env.Append(LINKFLAGS=[
])

env.Program(target = build_filename, source = sources)
