#!/usr/bin/python
# This is a SCons script that builds a java project.

import os

env = Environment()
env.Append(JAVACFLAGS = ["-cp", "src/blacken.jar"])

executable = 'build/a.jar'
sources = Glob('src')  # Add the the java source files.
cls = env.Java(target = 'classes', source = sources)
cls = Glob('classes/*')
cls.append('src/MANIFEST.MF') # Add the manifest file.

env.Jar(target = executable, source = cls)

