#!/usr/bin/python
# This is a SCons script that builds a java project.

import os

env = Environment()

executable = 'build/a.jar'
sources = Glob('src/*.java')  # Add the the java source files.

cls = Java(target = 'classes', source = sources)
cls.append('src/MANIFEST.MF') # Add the manifest file.

Jar(target = executable, source = cls)
Execute(Chmod(executable, 0755))

#Depends(dep1, dep2)
