# This is a SCons script that builds a C++ project.

import os

env = Environment(ENV=os.environ)

build_filename = '../build/a.out'

sources = [
	Glob('*.cpp'),		# Add all cpp files.
]

env.Append(CCFLAGS=[
	'-Wall',
	'-g'
])

env.Append(LIBS = [
	'SDL2_ttf',
	#'-lglew32',
	#'-lopengl32',
	#'-lglu32'
])

env.ParseConfig('sdl2-config --cflags')
env.ParseConfig('sdl2-config --libs')
#env.ParseConfig('pkg-config --cflags --libs SDL2_ttf')


env.Program(target = build_filename, source = sources)

